backend:
  name: git-gateway
  repo: rhgrads/rhgrads
  branch: master # Branch to update
publish_mode: editorial_workflow
media_folder: "static/images" # Media files will be stored in the repo under static/images
public_folder: "/images" # The src attribute for uploaded media will begin with /images
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}-{{year}}-{{month}}-{{day}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Job Title", name: "jobtitle", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "jobs" # Used in routes, e.g., /admin/collections/blog
    label: "Job Postings" # Used in the UI
    folder: "content/jobs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}-{{year}}-{{month}}-{{day}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Job Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Job Starting Date", name: "startdate", widget: "date"}
      - {label: "Application Closing Date", name: "closingdate", widget: "date"}
      - {label: "Job Description", name: "body", widget: "markdown"}
      - {label: "Primary job responsibilities", name: "description", widget: "markdown"}
      # - {label: "Required Skills", name: "skills", widget: "markdown"}
